### PR TITLE
Resolve hostnames before using ping

### PR DESCRIPTION
**Pull request by joecks**
net-ping only pings ip addresses, but it is often useful to ping hosts or
ddns entries, like local devices. Now it is possible to ping "your-dev.local".

### CODE REVIEW

**Comment by sweetpi** [comment]
Thanks for the pull request. Does it still work with ip addresses?

**Comment by sweetpi** [comment]
Released with v0.8.4.

**Comment by pimagical** [comment]
It dont work with ip addresses anymore! Al my devices and google website ip and my phones are false now. Do i have a local problem or isnt it been tested before? DDNS addresses are working fine.

**Comment by sweetpi** [comment]
@pimagical Should be working again now :)

**Comment by pimagical** [comment]
Thanks for your fast update and response, ip addresses are working fine again 😅 ddns still to!

**Comment by joecks** [comment]
Hmm I should check my notifications for github, didn't see your comment. 
Thanks for the patch!

**Pull request merged**
